# Generated by Django 5.1.6 on 2025-09-24 06:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUserLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(db_index=True, max_length=150)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('action', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('detail', models.TextField(blank=True, db_index=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'admin_feature_userlog',
                'indexes': [models.Index(fields=['timestamp'], name='admin_user__timesta_3c0422_idx'), models.Index(fields=['username'], name='admin_user__usernam_90b206_idx'), models.Index(fields=['email'], name='admin_user__email_a7f857_idx'), models.Index(fields=['detail'], name='admin_user__detail_fce9d1_idx'), models.Index(fields=['action'], name='admin_user__action_306e32_idx')],
            },
        ),
    ]
