# Generated by Django 5.1.6 on 2025-10-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_feature', '0002_add_timestamp_and_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='PtBackendUser',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'pt_backend_user',
                'managed': False,
            },
        ),
        migrations.RemoveIndex(
            model_name='adminuserlog',
            name='admin_user__detail_fce9d1_idx',
        ),
        migrations.RenameIndex(
            model_name='adminuserlog',
            new_name='admin_featu_timesta_d56a39_idx',
            old_name='admin_user__timesta_3c0422_idx',
        ),
        migrations.RenameIndex(
            model_name='adminuserlog',
            new_name='admin_featu_usernam_6e8390_idx',
            old_name='admin_user__usernam_90b206_idx',
        ),
        migrations.RenameIndex(
            model_name='adminuserlog',
            new_name='admin_featu_email_da66b3_idx',
            old_name='admin_user__email_a7f857_idx',
        ),
        migrations.RenameIndex(
            model_name='adminuserlog',
            new_name='admin_featu_action_b4a740_idx',
            old_name='admin_user__action_306e32_idx',
        ),
    ]
