# Generated by Django 5.1.6 on 2025-11-03 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_feature', '0003_ptbackenduser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuserlog',
            name='action',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='adminuserlog',
            name='detail',
            field=models.TextField(blank=True, db_index=True, default=''),
        ),
        migrations.AlterField(
            model_name='adminuserlog',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
