# Generated by Django 5.1.6 on 2025-11-02 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('file_name', models.CharField(max_length=255)),
                ('last_edited', models.DateTimeField()),
                ('submitted_by', models.CharField(db_index=True, max_length=64)),
            ],
            options={
                'db_table': 'expert_dataset',
                'ordering': ['-last_edited'],
            },
        ),
    ]
