# Generated by Django 5.1.6 on 2025-11-08 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert_user_feature', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertDatasetRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('data_id', models.CharField(max_length=64)),
                ('gender', models.CharField(max_length=16)),
                ('age', models.IntegerField()),
                ('city', models.CharField(max_length=128)),
                ('status', models.CharField(max_length=64)),
                ('disease_id', models.CharField(max_length=64)),
                ('location_id', models.CharField(max_length=64)),
                ('severity', models.CharField(max_length=64)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='expert_user_feature.expertdataset')),
            ],
            options={
                'db_table': 'expert_dataset_row',
                'ordering': ['row_number'],
                'indexes': [models.Index(fields=['dataset', 'row_number'], name='expert_data_dataset_570dbd_idx'), models.Index(fields=['data_id'], name='expert_data_data_id_eb73eb_idx')],
            },
        ),
    ]
