# Generated by Django 5.1.6 on 2025-11-09 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert_user_feature', '0002_expertdatasetrow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertdataset',
            name='submitted_by',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='expertdatasetrow',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expertdatasetrow',
            name='city',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='expertdatasetrow',
            name='disease_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='expertdatasetrow',
            name='gender',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='expertdatasetrow',
            name='location_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='expertdatasetrow',
            name='severity',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='expertdatasetrow',
            name='status',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.CreateModel(
            name='ExpertDataLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('data_id', models.UUIDField()),
                ('title', models.CharField(max_length=255)),
                ('last_edited', models.DateTimeField(auto_now_add=True)),
                ('submitted_by', models.CharField(max_length=150)),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'expert_feature_datalog',
                'ordering': ['-last_edited'],
                'default_permissions': ('add', 'view'),
                'indexes': [models.Index(fields=['data_id'], name='expert_feat_data_id_37f65c_idx'), models.Index(fields=['submitted_by'], name='expert_feat_submitt_3ab88e_idx'), models.Index(fields=['-last_edited'], name='expert_feat_last_ed_cf1da8_idx')],
            },
        ),
    ]
