# Map of Indonesian province names to ISO 3166-2 codes
PROVINCE_TO_CODE = {
    'Aceh': 'ID-AC',
    'Bali': 'ID-BA',
    'Bangka Belitung': 'ID-BB',
    'Banten': 'ID-BT',
    'Bengkulu': 'ID-BE',
    'DI Yogyakarta': 'ID-YO',
    'DKI Jakarta': 'ID-JK',
    'Gorontalo': 'ID-GO',
    'Jambi': 'ID-JA',
    'Jawa Barat': 'ID-JB',
    'Jawa Tengah': 'ID-JT',
    'Jawa Timur': 'ID-JI',
    'Kalimantan Barat': 'ID-KB',
    'Kalimantan Selatan': 'ID-KS',
    'Kalimantan Tengah': 'ID-KT',
    'Kalimantan Timur': 'ID-KI',
    'Kalimantan Utara': 'ID-KU',
    'Kepulauan Riau': 'ID-KR',
    'Lampung': 'ID-LA',
    'Maluku': 'ID-MA',
    'Maluku Utara': 'ID-MU',
    'Nusa Tenggara Barat': 'ID-NB',
    'Nusa Tenggara Timur': 'ID-NT',
    'Papua': 'ID-PA',
    'Papua Barat': 'ID-PB',
    'Papua Barat Daya': 'ID-PD',
    'Papua Pegunungan': 'ID-PP',
    'Papua Selatan': 'ID-PS',
    'Papua Tengah': 'ID-PT',
    'Riau': 'ID-RI',
    'Sulawesi Barat': 'ID-SR',
    'Sulawesi Selatan': 'ID-SN',
    'Sulawesi Tengah': 'ID-ST',
    'Sulawesi Tenggara': 'ID-SG',
    'Sulawesi Utara': 'ID-SA',
    'Sumatera Barat': 'ID-SB',
    'Sumatera Selatan': 'ID-SS',
    'Sumatera Utara': 'ID-SU'
}

PROVINCE_ALIASES = {
    'aceh': 'Aceh',
    'nanggroe aceh darussalam': 'Aceh',
    'bali': 'Bali',
    'bangka belitung': 'Bangka Belitung',
    'bangka-belitung': 'Bangka Belitung',
    'kepulauan bangka belitung': 'Bangka Belitung',
    'kep. bangka belitung': 'Bangka Belitung',
    'bangka belitung islands': 'Bangka Belitung',
    'banten': 'Banten',
    'bengkulu': 'Bengkulu',
    'di yogyakarta': 'DI Yogyakarta',
    'daerah istimewa yogyakarta': 'DI Yogyakarta',
    'd.i. yogyakarta': 'DI Yogyakarta',
    'diy': 'DI Yogyakarta',
    'special region of yogyakarta': 'DI Yogyakarta',
    'special region of jogjakarta': 'DI Yogyakarta',
    'dki jakarta': 'DKI Jakarta',
    'dki jakarta raya': 'DKI Jakarta',
    'daerah khusus ibukota jakarta': 'DKI Jakarta',
    'jakarta': 'DKI Jakarta',
    'special capital region of jakarta': 'DKI Jakarta',
    'gorontalo': 'Gorontalo',
    'jambi': 'Jambi',
    'jawa barat': 'Jawa Barat',
    'west java': 'Jawa Barat',
    'jawa tengah': 'Jawa Tengah',
    'central java': 'Jawa Tengah',
    'jawa timur': 'Jawa Timur',
    'east java': 'Jawa Timur',
    'kalimantan barat': 'Kalimantan Barat',
    'west kalimantan': 'Kalimantan Barat',
    'kalimantan selatan': 'Kalimantan Selatan',
    'south kalimantan': 'Kalimantan Selatan',
    'kalimantan tengah': 'Kalimantan Tengah',
    'central kalimantan': 'Kalimantan Tengah',
    'kalimantan timur': 'Kalimantan Timur',
    'east kalimantan': 'Kalimantan Timur',
    'kalimantan utara': 'Kalimantan Utara',
    'north kalimantan': 'Kalimantan Utara',
    'kepulauan riau': 'Kepulauan Riau',
    'riau islands': 'Kepulauan Riau',
    'lampung': 'Lampung',
    'maluku': 'Maluku',
    'maluku utara': 'Maluku Utara',
    'north maluku': 'Maluku Utara',
    'nusa tenggara barat': 'Nusa Tenggara Barat',
    'west nusa tenggara': 'Nusa Tenggara Barat',
    'nusa tenggara timur': 'Nusa Tenggara Timur',
    'east nusa tenggara': 'Nusa Tenggara Timur',
    'papua': 'Papua',
    'papua barat': 'Papua Barat',
    'west papua': 'Papua Barat',
    'papua barat daya': 'Papua Barat Daya',
    'southwest papua': 'Papua Barat Daya',
    'papua pegunungan': 'Papua Pegunungan',
    'highland papua': 'Papua Pegunungan',
    'highlands papua': 'Papua Pegunungan',
    'papua selatan': 'Papua Selatan',
    'south papua': 'Papua Selatan',
    'papua tengah': 'Papua Tengah',
    'central papua': 'Papua Tengah',
    'riau': 'Riau',
    'sulawesi barat': 'Sulawesi Barat',
    'west sulawesi': 'Sulawesi Barat',
    'sulawesi selatan': 'Sulawesi Selatan',
    'south sulawesi': 'Sulawesi Selatan',
    'sulawesi tengah': 'Sulawesi Tengah',
    'central sulawesi': 'Sulawesi Tengah',
    'sulawesi tenggara': 'Sulawesi Tenggara',
    'southeast sulawesi': 'Sulawesi Tenggara',
    'sulawesi utara': 'Sulawesi Utara',
    'north sulawesi': 'Sulawesi Utara',
    'sumatera barat': 'Sumatera Barat',
    'west sumatra': 'Sumatera Barat',
    'sumatera selatan': 'Sumatera Selatan',
    'south sumatra': 'Sumatera Selatan',
    'sumatera utara': 'Sumatera Utara',
    'north sumatra': 'Sumatera Utara',
}

# Climate data validation error messages
CLIMATE_ERROR_INVALID_FORMAT = "Invalid data format"
CLIMATE_ERROR_MISSING_PROVINCE = "Missing province field"
CLIMATE_ERROR_INVALID_VALUE = "Invalid value type" 

