# Generated by Django 5.1.6 on 2025-05-21 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pt_backend', '0017_user_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('metric', models.CharField(choices=[('jumlah_kasus', 'Jumlah Kasus'), ('estimasi_prevalensi', 'Estimasi Prevalensi'), ('usia', 'Usia'), ('jenis_kelamin', 'Jenis Kelamin'), ('tingkat_kasus', 'Tingkat Kasus'), ('distribusi_sumber_berita', 'Distribusi Sumber Berita')], max_length=64)),
                ('file_format', models.CharField(choices=[('png', 'PNG'), ('jpg', 'JPG'), ('jpeg', 'JPEG')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='downloadevent',
            index=models.Index(fields=['metric', 'created_at'], name='pt_backend_downlo_metric_5eee9f_idx'),
        ),
    ]
