# Generated by Django 5.1.6 on 2025-10-19 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pt_backend', '0017_user_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
