# Generated by Django 5.1.6 on 2025-11-03 05:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pt_backend', '0019_case_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseUploadBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_batches', to='pt_backend.user')),
            ],
            options={
                'ordering': ('-uploaded_at',),
            },
        ),
        migrations.AddField(
            model_name='case',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='pt_backend.caseuploadbatch'),
        ),
    ]