"""
Django settings for pantau_tular project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
import sys
from pathlib import Path
from dotenv import load_dotenv
import dj_database_url
from datetime import timedelta
try:
    from csp.constants import SELF
except ImportError:
    SELF = "'self'"

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv()

TESTING = any(arg.lower() == "test" for arg in sys.argv)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'unsafe-default-secret-key')
SECRET_API_KEY = os.getenv('SECRET_API_KEY', 'test-api-key')
ENABLE_DOWNLOAD_LOGGING = os.getenv("ENABLE_DOWNLOAD_LOGGING", "false").lower() == "true"
_secret_keys_env = [item.strip() for item in os.getenv("SECRET_API_KEYS", "").split(",") if item.strip()]
SECRET_API_KEYS = tuple(dict.fromkeys([SECRET_API_KEY, *_secret_keys_env]))

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False
# print("DEBUG =", DEBUG)

# settings.py
PASSWORD_RESET_TIMEOUT = 60 * 15  # 15 menit (default)

DISABLE_PASSWORD_RESET_THROTTLE = os.getenv(
    "DISABLE_PASSWORD_RESET_THROTTLE",
    "true" if TESTING else "false",
).lower() == "true"

DISABLE_API_KEY_FOR_FILTERS = os.getenv(
    "DISABLE_API_KEY_FOR_FILTERS",
    "true" if TESTING else "false",
).lower() == "true"

ALLOWED_HOSTS = os.getenv(
    "ALLOWED_HOSTS",
    "localhost,127.0.0.1,.up.railway.app,.koyeb.app"
).split(",")

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'pt_backend',
    'csp',
    'rest_framework',
    'hello',
    'corsheaders',
    'django_prometheus',
    'authentication',
    'rest_framework_simplejwt',
    'admin_feature', 
    'curator_feature',
    'expert_user_feature',

]

MIDDLEWARE = [
    'django_prometheus.middleware.PrometheusBeforeMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'csp.middleware.CSPMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_prometheus.middleware.PrometheusAfterMiddleware',
]

REST_FRAMEWORK = {
    "DEFAULT_THROTTLE_RATES": {
        "user": "10/min",   
        "password_reset": "5/day",
    },
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
}

ACCOUNT_LOCKOUT = {
    'MAX_FAILED_ATTEMPTS': 5,
    'LOCKOUT_DURATION': 60 * 15, 
}

ROOT_URLCONF = 'pantau_tular.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pantau_tular.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASE_URL = os.getenv('DATABASE_URL')

if DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.config(default=DATABASE_URL)
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Force lightweight SQLite DB when executing automated tests (manage.py test / pytest)
RUNNING_TESTS = (
    os.environ.get("PYTEST_CURRENT_TEST")
    or os.environ.get("DJANGO_TEST", "").lower() in {"1", "true"}
    or any(arg in {"test", "testserver", "pytest"} for arg in sys.argv)
)

if RUNNING_TESTS:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'test_db.sqlite3',
        }
    }

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "unique-cache",
    }
}



# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

CORS_ALLOWED_ORIGINS = [
    "https://pantautular.netlify.app",
    "https://keen-jewelle-samuellapnadia-71c13d07.koyeb.app",
]


CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^http://localhost:\d+$",
    r"^https:\/\/.*\.up\.railway\.app$",  # Allows all railway.app subdomains
    r"^https:\/\/.*\.netlify\.app$",  # Allows all netlify.app subdomains
    r"^https:\/\/.*\.koyeb\.app$",
]

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'x-api-key',
]

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Security Settings
SESSION_COOKIE_SECURE = True  # Set to True in production with HTTPS
CSRF_COOKIE_SECURE = True    # Set to True in production with HTTPS
SECURE_SSL_REDIRECT = False  # Set to True in production to force HTTPS
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_HSTS_SECONDS = 31536000  # 1 year
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

CONTENT_SECURITY_POLICY = {
    'default-src': SELF,
    'script-src': [SELF, 'https://cdn.jsdelivr.net', 'https://cdnjs.cloudflare.com'],
    'style-src': [SELF, 'https://fonts.googleapis.com', 'https://cdn.jsdelivr.net'],
    'font-src': [SELF, 'https://fonts.gstatic.com'],
    'img-src': [SELF, 'data:', 'https:'],
    'connect-src': [SELF, 'https://api.github.com'],
    'frame-ancestors': ["'none'"],
    'base-uri': ["'self'"],
    'form-action': ["'self'"],
    'object-src': ["'none'"],
}

# CSP Configuration Options
# CSP_REPORT_URI = '/csp-violation-report/'  # Uncomment to enable violation reporting

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False

CSRF_TRUSTED_ORIGINS = [
    "https://keen-jewelle-samuellapnadia-71c13d07.koyeb.app",  # FE
    "https://royal-rahel-nayaka-cbe367a7.koyeb.app",           # BE
    "https://pantautular.netlify.app",
]


# sane defaults for curator role settings
CURATOR_ROLE_NAME = "CURATOR"
# which checks to use in IsCuratorRole: "role" attr on user, Django group membership
CURATOR_ROLE_CHECKS = ("role", "group")

if 'test' in sys.argv:
    MIGRATION_MODULES = {
        'curator_feature': None,  # ⛔ skip all migrations for this app
    }
