# Generated by Django 5.1.6 on 2025-11-19 09:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CuratedTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('summary', models.TextField(blank=True, null=True)),
                ('source_url', models.URLField(unique=True)),
                ('source_name', models.CharField(db_index=True, max_length=255)),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
                ('published_at', models.DateTimeField(db_index=True)),
                ('is_curated', models.BooleanField(db_index=True, default=False)),
                ('curator_note', models.TextField(blank=True, null=True)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('curated_tags', models.ManyToManyField(blank=True, related_name='articles', to='news_feature.curatedtag')),
            ],
            options={
                'ordering': ('-published_at', '-created_at'),
            },
        ),
    ]
