# Generated by Django 5.1.6 on 2025-11-19 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_feature', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
