# Generated by Django 5.1.6 on 2025-11-20 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_feature', '0002_alter_newsarticle_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='curator_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='thumbnail_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
