# Generated by Django 5.1.6 on 2025-11-19 10:12

import contributor_feature.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pt_backend', '0024_alter_case_options_alter_case_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributorApprovalRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contributor_approval_role', to='pt_backend.role')),
            ],
            options={
                'verbose_name': 'Contributor approval role',
                'verbose_name_plural': 'Contributor approval roles',
                'db_table': 'contributor_feature_approval_roles',
                'ordering': ('role__name',),
            },
        ),
        migrations.CreateModel(
            name='ContributorCaseSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gender', models.CharField(max_length=10)),
                ('age', models.PositiveIntegerField()),
                ('city', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('minimal', 'Minimal'), ('biasa', 'Biasa'), ('bahaya', 'Bahaya'), ('katastropik', 'Katastropik')], max_length=20)),
                ('severity', models.CharField(choices=[('hospitalisasi', 'Hospitalisasi'), ('insiden', 'Insiden'), ('mortalitas', 'Mortalitas')], max_length=255)),
                ('news_payload', models.JSONField(blank=True, default=contributor_feature.models._default_news_payload)),
                ('state', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20)),
                ('review_note', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_contributor_submissions', to='pt_backend.case')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributor_submissions', to='pt_backend.user')),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contributor_submissions', to='pt_backend.disease')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contributor_submissions', to='pt_backend.location')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_contributor_submissions', to='pt_backend.user')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributor_submissions_updated', to='pt_backend.user')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['state', '-created_at'], name='contributor_state_ae119f_idx'), models.Index(fields=['created_by', '-created_at'], name='contributor_created_f590b7_idx')],
            },
        ),
    ]
