
# Generated by Django 5.1.6 on 2025-10-09 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True
    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackendCase',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('disease_id', models.UUIDField(blank=True, null=True)),
                ('location_id', models.UUIDField(blank=True, null=True)),
                ('severity', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'pt_backend_case',
                'managed': False,
            },
        ),
    ]

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DownloadLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("username", models.CharField(max_length=255)),
                ("chart_type", models.CharField(max_length=255)),
                ("timestamp", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "download_logs",
                "ordering": ("-created_at",),
            },
        ),
    ]
 