# Generated by Django 5.1.6 on 2025-10-19 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curator_feature', '0002_dashboarddownloadevent'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='dashboarddownloadevent',
            new_name='dashboard_d_metric_f1255d_idx',
            old_name='curator_fe_metric_7b5779_idx',
        ),
    ]
