# Generated by Django 5.1.6 on 2025-10-20 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curator_feature', '0003_rename_curator_fe_metric_7b5779_idx_dashboard_d_metric_f1255d_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackendCase',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('disease_id', models.UUIDField(blank=True, null=True)),
                ('location_id', models.UUIDField(blank=True, null=True)),
                ('severity', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'pt_backend_case',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuratorDataLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('data_id', models.UUIDField()),
                ('title', models.CharField(max_length=255)),
                ('last_edited', models.DateTimeField(auto_now_add=True)),
                ('submitted_by', models.CharField(max_length=150)),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'curator_feature_datalog',
                'ordering': ['-last_edited'],
                'indexes': [models.Index(fields=['data_id'], name='curator_fea_data_id_cc05dc_idx'), models.Index(fields=['submitted_by'], name='curator_fea_submitt_138c9a_idx'), models.Index(fields=['-last_edited'], name='curator_fea_last_ed_e8212f_idx')],
            },
        ),
    ]
