# Generated by Django 5.1.6 on 2025-10-20 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curator_feature', '0004_backendcase_curatordatalog'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('portal', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'pt_backend_news',
                'managed': False,
            },
        ),
    ]
