# Generated by Django 5.1.6 on 2025-11-18 12:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("curator_feature", "0008_curatordatalog_note_default"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dashboarddownloadevent",
            name="client_ip",
            field=models.CharField(
                blank=True,
                default="",
                max_length=45,
                validators=[django.core.validators.validate_ipv46_address],
            ),
        ),
    ]
