# Generated by Django 5.1.6 on 2025-11-24 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curator_feature', '0009_alter_dashboarddownloadevent_client_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributorSubmission',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True, default='')),
                ('submitted_by', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('WAITING_FOR_APPROVAL', 'Waiting for Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('NEED_REVISION', 'Need Revision')], default='WAITING_FOR_APPROVAL', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'contributor_submissions',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['submitted_by'], name='contributor_submitt_726aa5_idx'), models.Index(fields=['status'], name='contributor_status_1ba1d1_idx'), models.Index(fields=['title'], name='contributor_title_f51ed4_idx')],
            },
        ),
    ]
